<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WindowsPrivacyPlatform.Models\WindowsPrivacyPlatform.Models.csproj" />
    <ProjectReference Include="..\WindowsPrivacyPlatform.Core\WindowsPrivacyPlatform.Core.csproj" />
    <ProjectReference Include="..\WindowsPrivacyPlatform.Logging\WindowsPrivacyPlatform.Logging.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="8.0.1" />
  </ItemGroup>

</Project>
