<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WindowsPrivacyPlatform.Models\WindowsPrivacyPlatform.Models.csproj" />
    <ProjectReference Include="..\WindowsPrivacyPlatform.Core\WindowsPrivacyPlatform.Core.csproj" />
    <ProjectReference Include="..\WindowsPrivacyPlatform.Logging\WindowsPrivacyPlatform.Logging.csproj" />
    <ProjectReference Include="..\WindowsPrivacyPlatform.KnowledgeBase\WindowsPrivacyPlatform.KnowledgeBase.csproj" />
    <ProjectReference Include="..\WindowsPrivacyPlatform.Validator\WindowsPrivacyPlatform.Validator.csproj" />
    <ProjectReference Include="..\WindowsPrivacyPlatform.Scanner\WindowsPrivacyPlatform.Scanner.csproj" />
  </ItemGroup>

</Project>
